name       : opera-stable
version    : 71.0.3770.198
release    : 128
source     :
    - https://get.geo.opera.com/pub/opera/desktop/71.0.3770.198/linux/opera-stable_71.0.3770.198_amd64.deb : d44af29613a8eb00ea54e63a74ce48d601131b239e191c695cc6124bb746a00f
license    : Distributable
homepage   : https://www.opera.com
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - ffmpeg-chromium
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib
    install -dm00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
