name       : opera-stable
version    : 44.0.2510.1159
release    : 35
source     :
    - http://operasoftware.pc.cdn.bitgravity.com/pub/opera/desktop/44.0.2510.1159/linux/opera-stable_44.0.2510.1159_amd64.deb : 6e90f1794a152cf1990300bd087502642117421e2b9b5f1b9f88455f02b188ee
license    : Distributable
extract    : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm 00755 $installdir/usr/bin
    install -dm 00644 $installdir/usr/lib
    install -dm 00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera
