name       : opera-stable
version    : 91.0.4516.65
release    : 216
source     :
    - https://get.geo.opera.com/pub/opera/desktop/91.0.4516.65/linux/opera-stable_91.0.4516.65_amd64.deb : 55a78ca1d8f47d6eb13b6e833498b2fc0e2994e72f20aae6e2892f29848486bd
license    : Distributable
homepage   : https://www.opera.com
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - ffmpeg-chromium-opera
rundeps    :
    - ffmpeg-chromium-opera
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib
    install -dm00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
