name       : opera-stable
version    : 56.0.3051.31
release    : 60
source     :
    - https://get.geo.opera.com/pub/opera/desktop/56.0.3051.31/linux/opera-stable_56.0.3051.31_amd64.deb : 6e59ff40b6bd4022c372dd064bbdcb95e3dff9070f57b0a52083c06823e8e005
license    : Distributable
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - ffmpeg-chromium
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm 00755 $installdir/usr/bin
    install -dm 00644 $installdir/usr/lib
    install -dm 00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
