name       : opera-stable
version    : 81.0.4196.60
release    : 176
source     :
    - https://get.geo.opera.com/pub/opera/desktop/81.0.4196.60/linux/opera-stable_81.0.4196.60_amd64.deb : c5cbcd109ed5133619008fc016a9d755e43c690b875eaa9f78917efd1b710e0b
license    : Distributable
homepage   : https://www.opera.com
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - ffmpeg-chromium
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib
    install -dm00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
