name       : opera-stable
version    : 44.0.2510.857
release    : 34
source     :
    - http://operasoftware.pc.cdn.bitgravity.com/pub/opera/desktop/44.0.2510.857/linux/opera-stable_44.0.2510.857_amd64.deb : d517a0969d5cd69de15c59bc0161d5230dc4065833cafe70634d5241ea4d50b9
license    : Distributable
extract    : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm 00755 $installdir/usr/bin
    install -dm 00644 $installdir/usr/lib
    install -dm 00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera
