name       : opera-stable
version    : 51.0.2830.26
release    : 50
source     :
    - http://download4.operacdn.com/pub/opera/desktop/51.0.2830.26/linux/opera-stable_51.0.2830.26_amd64.deb : 67e221f7b5bb2074036fd9e334f58628c174a611a06997c360e68667a31b3e8f
license    : Distributable
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm 00755 $installdir/usr/bin
    install -dm 00644 $installdir/usr/lib
    install -dm 00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera
