name       : opera-stable
version    : 63.0.3368.66
release    : 92
source     :
    - https://get.geo.opera.com/pub/opera/desktop/63.0.3368.66/linux/opera-stable_63.0.3368.66_amd64.deb : 13f87458301836fdddc0151e31182950ff4deeac9d028314c566824c3e69527a
license    : Distributable
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangocairo)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - ffmpeg-chromium
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
build      : |
    cd root
    chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib
    install -dm00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
